FROM node:14.17-alpine as build

WORKDIR /usr/local/app

COPY ./package.json ./
COPY ./yarn.lock ./

RUN yarn install
RUN yarn run build
COPY . .

EXPOSE 5000
FROM nginx:latest

COPY --from=build /usr/local/app/dist/team5_front_end/usr/share/nginx/html .
CMD ["./app"]  